site_name: Technical
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  custom_dir: custom_theme
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking
    - navigation.top

plugins:
  - search:
      lang: vi
  - plantuml:
      # puml_url: https://www.plantuml.com/plantuml/
      puml_url: http://localhost:8080/
  - graph
  - macros

nav:
  ##################################################################################################################################
  # - Giới Thiệu Computing: index.md
  - Computing: 
    - Computing: index.md
    - Computer Architecture: Computing/computer-architecture.md
    - Operating System: Computing/os.md
    - Linux:
      - Linux Getting Start: Computing/linux.md
      - Sổ Tay Người Dùng Linux: Computing/linux-distribution-user-manual.md
      - Linux Terminal Shell: Computing/linux-terminal-shell.md
      - Linux System Internals: Computing/linux-system-internals.md
    - Zorin: Computing/zorin.md
    - Windows: Computing/windows.md
    - Android:
      - Android: Computing/android.md
      - Android Core:
        - Android Core: Computing/android-core.md
      - Android ADB: Computing/android-adb.md
    - RTOS: Computing/rtos.md
    - Digital Standards:
      - Digital Standards: Computing/digital-standards.md
      - Network:
        - Chữ Ký Số: Computing/digital-signature.md
        - Điều Chế/Giải Điều Chế: Computing/telecom-signal-modulation.md
      - Audio:
        - Audio: Computing/audio.md
        - Audio Study Concept: Computing/audio-study-concept.md
        - File Types:
          - WAV: Computing/audio-wav.md
          - MP3: Computing/audio-mp3.md
          - FLAC: Computing/audio-flac.md
      - Video:
        - Video: Computing/video.md
    - AI:
      - AI: Computing/ai.md
##################################################################################################################################
  - Programming:
    - Programming: Programming/programming.md
    - Complied Language:
      - C: Programming/c.md
      - C++: Programming/cpp.md
      - C#: Programming/csharp.md
      - Rust: Programming/rust.md
    - Interpreted/Hybrid:
      - Python: Programming/python.md
      - Java: Programming/java.md
      - Kotlin: Programming/kotlin.md
      - Javascript: Programming/Javascript.md
    - Web:
      - HTML: Programming/html.md
      - CSS: Programming/css.md
    - Assembly:
      - Assembly: Programming/assembly.md
  - Developer:
    - Developer: Dev/dev.md
    - Libraries: Dev/libs.md
    - Frameworks:
      - ROS2: Dev/ros2.md
    - Version Control:
      - Git: Dev/git.md
      - Git Tools: Dev/git-tools.md
      - Repo: Dev/repo.md
      - SVN: Dev/svn.md
    - Tools:
      - VSCode: Dev/vscode.md
    - Build System:
      - GNU: Programming/gnu.md
      - LLVM: Programming/llvm.md
      - Clang: Programming/clang.md
    - Meta-Build System:
      - Make: Programming/make.md
      - CMake: Programming/cmake.md
      - Yocto: Programming/yocto.md
##################################################################################################################################
  - Android:
    - Android OS: Computing/Android/android.md
    - Android Base:
      - Android ABI: Computing/Android/android-abi.md
    - Android Core:
      - Android Core: Computing/Android/android-core.md
      - Android Architecture: Computing/Android/android-core-architecture.md
      - HAL:
        - HAL: Computing/Android/android-core-architecture-hal.md
      - Kernel:
        - SELinux: Computing/Android/android-core-architecture-hal.md
    - Application:
      - Android Application:
        - Android Application: Computing/Android/android-application.md
        - App Architecture: Computing/Android/android-app-architecture.md
        - UI Layer:
          - Android Activity: Computing/Android/android-activity.md
          - Android Fragment: Computing/Android/android-fragment.md
        - Component:
          - ListView: Computing/Android/android-dev-app-listview.md
      - Menu Option: Computing/Android/android-dev-menu-option.md
    - Android Debug:
      - ADB:
        - ADB: Computing/Android/android-adb.md
        - ADB Logcat: Computing/Android/android-adb-logcat.md
        - ADB ETH: Computing/Android/android-adb-eth.md
        - ADB Bugreport: Computing/Android/android-adb-bugreport.md
      - Proto: Computing/Android/android-bugreport-proto.md
    - External:
      - Tinyalsa: Computing/Android/android-core-external-tinyalsa.md
      - JNI:
        - Create JNI: Computing/Android/android-dev-application-jni.md
        - JNI Type: Computing/Android/android-dev-jni-type.md
    - Misc:
      # Phần này tôi để trong những cái mình không biết nó nên thuộc module nào thì đưa vào đây.
      - Enable App Optimization: Computing/Android/android-enable-app-optimization.md
      - Systrace: Computing/Android/android-systrace.md
    - Example:
      - First Application: Computing/Android/android-first-application.md
  ##################################################################################################################################
  - Tools:
    - Tools: Tools/tools.md
    - Terminal:
      - sambashare: Tools/sambashare.md
      - minicom: Tools/minicom.md
      - tmux: Tools/tmux.md
      - tree: Tools/tree.md
      - Docker: Tools/docker.md
      - FFmpeg: Tools/ffmpeg.md
      - yt-dlp: Tools/yt-dlp.md
      - NeoVim: Tools/nvim-text-editor.md
      - Helix: Tools/helix-text-editor.md
      - Terminator: Tools/terminator.md
      - mdbook: Tools/mdbook.md
    - Application Tools:
      - Putty: Tools/putty.md
      - 3Utool: Tools/3utools.md
      - Scrcpy: Tools/scrcpy.md
      - AnyDesk: Tools/anydesk.md
    - Misc:
      - MSYS2:
        - Overview: Tools/msys2.md
        - Install: Tools/msys2-install.md
        - Pacman: Tools/msys2-pacman.md
        - Package: Tools/msys2-package.md
  ##################################################################################################################################
  - Dev Tools:
    - Dev Tools: DevTools/dev-tools.md
    - NodeJS:
      - Overview: Tools/nodejs.md
      - Getting Start: Tools/nodejs-getting-start.md
    - Electron:
      - Electron: Tools/electron.md
      - Create App: Tools/electron-create-app.md
      - Load Link: Tools/electron-load-link.md
      - Troubleshoots: Tools/electron-troubleshoots.md
    - VSCode:
      - VSCode: DevTools/VSCode/software-vscode.md
      - Install VSCode: DevTools/VSCode/software-vscode-install.md
      - VSCode Config: DevTools/VSCode/software-vscode-config.md
      - VSCode Keybindings: DevTools/VSCode/software-vscode-keybindings.md
      - VSCode Snippets: DevTools/VSCode/software-vscode-snippets.md
      - VSCode Extensions: DevTools/VSCode/software-vscode-extensions.md
      - VSCode Custom: DevTools/VSCode/software-vscode-my-custom.md
      - VSCode Tasks: DevTools/VSCode/software-vscode-tasks.md
      - VSCode Trick: DevTools/VSCode/software-vscode-trick.md
      - Example:
        - Example Keybindings: DevTools/VSCode/example/company-keybindings-json.md
        - Example Markdown Snippets: DevTools/VSCode/example/company-snippets-for-markdown.md
    - Qt:
      - Qt: DevTools/Qt/qt.md
      - Qt Creator: DevTools/Qt/qt-software-qt-creator.md
      - Buikd Qt Source: DevTools/Qt/qt-build-qt-source.md
    - Android Studio:
      - Android Studio: DevTools/AndroidStudio/software-android-studio.md
      - Install Android Studio: DevTools/AndroidStudio/software-android-studio-install.md
      - Build System:
        - Gradle: DevTools/AndroidStudio/software-android-gradle.md
        - SDK: DevTools/AndroidStudio/software-android-studio-sdk.md
        - NDK: DevTools/AndroidStudio/software-android-studio-ndk.md
      - Config:
        - Keyboard: DevTools/AndroidStudio/software-android-studio-theme.md
        - Theme: DevTools/AndroidStudio/software-android-studio-theme.md
      - Troubleshoot: DevTools/AndroidStudio/software-android-studio-troubleshoot.md
    - Make:
      - Make: DevTools/Make/make.md
      - Install: DevTools/Make/make-install.md
      - Getting Start: DevTools/Make/make-getting-start.md
      - Template: DevTools/Make/make-template.md
    - Yocto:
      - Yocto: DevTools/Yocto/yocto.md
      - Bitbake: DevTools/Yocto/yocto-bitbake.md
    - Repo:
      - Repo: DevTools/Repo/repo.md
      - Repo for Win: DevTools/Repo/repo-windows.md
      - Inside .repo: DevTools/Repo/repo-repo-inside.md
  ##################################################################################################################################
  - MarkUp:
    - UML: Markup/UML/uml.md
    - UML Class Diagram: Markup/UML/uml-class-diagram.md
    - Markdown: Markup/Markdown/markdown.md
    - PlantUml: Markup/PlantUml/plantuml.md
    - Mermaid:
      - Mermaid: Markup/Mermaid/mermaid.md
    - MKDocs:
      - MKDocs: Markup/MKDocs/mkdocs.md
      - mkdocs tools: Markup/MKDocs/mkdocs_lv2.md
      - Theme:
        - Theme: Markup/MKDocs/mkdocs-theme.md
        - CSS: Markup/MKDocs/mkdocs-css.md
      - Plugins:
        - Plugins: Markup/MKDocs/mkdocs-plugins.md
        - Mermaid: Markup/MKDocs/mkdocs-mermaid.md
        - PlantUml: Markup/MKDocs/mkdocs-plantuml.md
      - Script:
        - Script: Markup/MKDocs/mkdocs-script.md
        - Katex: Markup/MKDocs/mkdocs-katex.md
        - Extensions: Markup/MKDocs/mkdocs-markdown-extensions.md
      - Publish:
        - Github Publish: Markup/MKDocs/mkdocs-github-publish.md
      - Clone Tad: Markup/MKDocs/mkdocs-clone-tad-style.md
      - Issue: Markup/MKDocs/mkdocs-issue.md
      - Projects: Markup/MKDocs/mkdocs-projects.md
      - TadApp: Markup/MKDocs/mkdocs-for-tadapp.md
  ##################################################################################################################################
  - Device:
    - Device: Device/electric.md
    - LKDT:
      - Điện Trở: Device/electric-resistor.md
    - Tham Khảo:
      - Reference: Device/electric-reference.md
    - Device:
      - Rasberry Pi: Device/rasberry-pi.md
      - Pi Android AOSP:
        - How To Build: Device/rasberry-pi-aosp.md
        - How To Use: Device/rasberry-pi-aosp-adb-wifi.md
      - CAN:
        - CANable 2.0: Device/canable.md
        - PEAK-System: Device/peak-system.md
        - SocketCAN: Device/socketcan.md 
  ##################################################################################################################################
  - Project:
    - Tad App: 
      - Windows: Project/project-tad-app-windows.md
      - Linux: Project/project-tad-app-linux.md
      - Tad Doc Script Build: Project/project-tad-app-build-doc.md
    - Pokedex: 
      - README: Project/project-pokedex.md
    - Ftxui Application:
      - Ftxui Application: Project/project-ftxui-application.md
    - Dự Thảo: Project/project-draff.md
extra_css:
  - assets/stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  # For table
  - pymdownx.blocks.html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      # custom_fences:
      #   - name: mermaid
      #     class: mermaid
      #     format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/tablesort.min.js
  - assets/scripts/tablesort.js
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

graph:
  enabled: true
  output_file: assets/network/graph.json
  include_homepage: true

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN

copyright:
  ☕ Made by Tad Zeila!