site_name: Technical
theme:
  name: material
  logo: assets/logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
  - graph

nav:
  ##################################################################################################################################
  - Common:
    - Preface: index.md
    - ❖ Mã Hoá:
      - Chữ Ký Số: Common/digital-signature.md
    - ❖ OS:
      - OS: OS/os.md
      - Endianness: OS/os-endianness.md
      - File System: OS/os-file-system.md
      - Audio:
        - PCM: OS/os-audio-pcm.md
        - Audio Sample Formats: OS/os-audio-sample-formats.md
    - AI: ai.md
  ##################################################################################################################################
  - Linux:
    - Overview & Install: OS/Linux/linux-family-overview-and-install.md
    - Install Ubuntu: OS/Linux/linux-install-ubuntu.md
    - ❖ Zorin:
      - Install Zorin: OS/Linux/linux-install-zorin.md
      - Menu App: OS/Linux/linux-zorin-menu-app.md
    - ❖ System:
      - System Info: OS/Linux/linux-system-info.md
      - Folder Hierarch: OS/Linux/linux-system-folder-hierarch.md
      - System File: OS/Linux/linux-system-file.md
      - Daemon: OS/Linux/linux-system-daemon.md
      - File: OS/Linux/linux-file.md
      - Alsa:
        - Alsa: OS/Linux/linux-alsa.md
        - aplay: OS/Linux/linux-alsa-aplay.md
        - amixer: OS/Linux/linux-alsa-amixer.md
      - Storage: OS/Linux/linux-storage.md
    - ❖ Tools:
      - iBamboo: OS/Linux/linux-tools-ibamboo.md
      - Grep: OS/Linux/linux-tools-grep.md
      - Tree: OS/Linux/linux-tools-tree.md
      - Minicom: OS/Linux/linux-tools-minicom.md
      - Tmux: OS/Linux/linux-tools-tmux.md
      - Compress: OS/Linux/linux-tools-compress-uncompress.md
      - Sed: OS/Linux/linux-tools-sed.md
      - NetCat: OS/Linux/linux-tools-netcat.md
    - ❖ Password:
      - Spec. Ubuntu 16 LST: OS/Linux/linux-ubuntu-16-lts-pass.md
    - ❖ Trick:
      - HTTP Server: OS/Linux/linux-http-server.md
      - Startup Script: OS/Linux/linux-startup-script.md
  ##################################################################################################################################
  - Windows:
    - Overview: OS/Windows/os-windows-overview.md
    - Một số lệnh thường dùng: OS/Windows/os-windows-cmd-common-command.md
    - ❖ System:
      - Services (WS): OS/Windows/os-windows-services.md
      - Macro PATH: OS/Windows/os-windows-common-path.md
      - Environment Variables: OS/Windows/os-windows-environment-variables.md
      - Startup Process: OS/Windows/os-windows-startup-process.md
      - Service Tag, Manufacture: OS/Windows/os-windows-service-tag-and-manufacture.md
      - Start Menu: OS/Windows/os-windows-service-start-menu.md
    - Network: OS/Windows/os-windows-network.md
    - ❖ Shell:
      - ❖ cmd:
        - cmd: OS/Windows/os-windows-cmd-getting-start.md
        - Command: OS/Windows/os-windows-cmd-command.md
        - Write Script: OS/Windows/os-windows-cmd-write-scripts.md
      - ❖ Power Shell:
        - Power Shell: OS/Windows/os-windows-ps-getting-start.md
      - ❖ Custom:
        - Usercmd: OS/Windows/os-windows-custom-usercmd.md
    - Regedit:
      - Regedit: OS/Windows/os-windows-regedit.md
      - Open with: OS/Windows/os-windows-custom-open-with.md
    - Key: OS/Windows/os-windows-buyed-key.md
    - Crack:
      - MAS: OS/Windows/os-windows-crack-by-mas.md
  ##################################################################################################################################
  - Android:
    - Android: OS/Android/android-overview.md
    - ❖ Tools:
      - ADB: OS/Android/android-adb.md
    - ❖ Application:
      - Activity: OS/Android/android-dev-app-activity.md
      - ListView:
        - ListView: OS/Android/android-dev-app-listview.md
        - ListView Custom: OS/Android/android-dev-app-listview-custom.md
      - Menu Option: OS/Android/android-dev-menu-option.md
    - ❖ JNI:
      - Create JNI: OS/Android/android-dev-application-jni.md
      - JNI Type: OS/Android/android-dev-jni-type.md
    - ❖ Android API:
      - Android API: OS/Android/android-api.md
    - ❖ Core:
      - Android Core: OS/Android/android-core.md
      - Architecture: OS/Android/android-core-architecture.md
      - ❖ HAL:
        - HAL: OS/Android/android-core-architecture-hal.md
    - ❖ Kernel:
      - SELinux: OS/Android/android-core-architecture-hal.md
    - ❖ External:
      - Tinyalsa: OS/Android/android-core-external-tinyalsa.md
    - ❖ Example:
      - First App: OS/Android/android-dev-first-application.md
  ##################################################################################################################################
  - Tools:
    - Tools: Tools/tools.md
    - ❖ MKDocs:
      - MKDocs: Tools/MKDocs/mkdocs.md
      - Theme: Tools/MKDocs/mkdocs-theme.md
      - CSS: Tools/MKDocs/mkdocs-css.md
      - Script: Tools/MKDocs/mkdocs-script.md
      - Plugins: Tools/MKDocs/mkdocs-plugins.md
      - Katex: Tools/MKDocs/mkdocs-katex.md
      - Mermaid: Tools/MKDocs/mkdocs-mermaid.md
      - PlantUml: Tools/MKDocs/mkdocs-plantuml.md
      - Extensions: Tools/MKDocs/mkdocs-markdown-extensions.md
      - Markdocs Github Publish: Tools/MKDocs/mkdocs-github-publish.md
      - Markdocs Lv2: Tools/MKDocs/mkdocs_lv2.md
      - Markdocs Clone Tad: Tools/MKDocs/mkdocs-clone-tad-style.md
      - Markdocs Issue: Tools/MKDocs/mkdocs-issue.md
      - Markdocs Projects: Tools/MKDocs/mkdocs-projects.md
      - MKDocs TadApp: Tools/MKDocs/mkdocs-for-tadapp.md
    - ❖ MSYS2:
      - Overview: Tools/msys2/msys2.md
      - Install: Tools/msys2/msys2-install.md
      - Pacman: Tools/msys2/msys2-pacman.md
      - Package: Tools/msys2/msys2-package.md
    - ❖ FFmpeg:
      - FFmpeg: Tools/FFmpeg/ffmpeg.md
      - Download: Tools/FFmpeg/ffmpeg-download.md
      - Convert: Tools/FFmpeg/ffmpeg-convert.md
    - ❖ NodeJS:
      - Overview: Tools/NodeJS/nodejs.md
      - Getting Start: Tools/NodeJS/nodejs-getting-start.md
    - ❖ Electron:
      - Electron: Tools/Electron/electron.md
      - Create App: Tools/Electron/electron-create-app.md
      - Load Link: Tools/Electron/electron-load-link.md
      - Troubleshoots: Tools/Electron/electron-troubleshoots.md
    - ❖ yt-dlp:
      - yt-dlp: Tools/yt-dlp/yt-dlp.md
    - 3Utool: Tools/Other/3utools.md
    - Putty: Tools/Other/putty.md
    - Sambashare: Tools/Other/sambashare.md
    - Scrcpy: Tools/Other/scrcpy.md
    - AnyDesk: Tools/AnyDesk/anydesk.md
    - ❖ Thảo luận:
      - IDE & Code Editor: Tools/Tools-paper-ide-code-editor.md
  ##################################################################################################################################
  - Dev Tools:
    - Dev Tools: DevTools/dev-tools.md
    - ❖ VSCode:
      - VSCode: DevTools/VSCode/software-vscode.md
      - Install: DevTools/VSCode/software-vscode-install.md
      - Settings: DevTools/VSCode/software-vscode-settings.md
      - Keybindings: DevTools/VSCode/software-vscode-keybindings.md
      - Snippets: DevTools/VSCode/software-vscode-snippets.md
      - Extensions: DevTools/VSCode/software-vscode-extensions.md
      - Custom: DevTools/VSCode/software-vscode-my-custom.md
      - Trick: DevTools/VSCode/software-vscode-trick.md
    - ❖ Android Studio:
      - Android Studio: DevTools/AndroidStudio/software-android-studio.md
      - Install: DevTools/AndroidStudio/software-android-studio-install.md
      - Gradle: DevTools/AndroidStudio/software-android-gradle.md
      - SDK: DevTools/AndroidStudio/software-android-studio-sdk.md
      - Theme: DevTools/AndroidStudio/software-android-studio-theme.md
      - Troubleshoot: DevTools/AndroidStudio/software-android-studio-troubleshoot.md
    - ❖ Qt:
      - Qt: DevTools/Qt/qt.md
      - QtCreator: DevTools/Qt/qt-software-qt-creator.md
    - ❖ Make:
      - Make: DevTools/Make/make.md
      - Install: DevTools/Make/make-install.md
      - Getting Start: DevTools/Make/make-getting-start.md
      - Template: DevTools/Make/make-template.md
    - ❖ Yocto:
      - Yocto: DevTools/Yocto/yocto.md
      - Bitbake: DevTools/Yocto/yocto-bitbake.md
    - ❖ Repo:
      - Repo: DevTools/Repo/repo.md
      - Repo for Win: DevTools/Repo/repo-windows.md
      - Inside .repo: DevTools/Repo/repo-repo-inside.md
  ##################################################################################################################################
  - Elec.:
    - Electronic: Electronic/electric.md
    - ❖ LKDT:
      - Điện Trở: Electronic/electric-resistor.md
  ##################################################################################################################################
  - Libs:
    - Libs: Libs/libs.md
    - ❖ FTXUI:
      - FTXUI: Libs/FTXUI/ftxui.md
      - Build: Libs/FTXUI/ftxui-build.md
      - Example: Libs/FTXUI/ftxui-example.md
    - ❖ NanoHTTPD:
      - Getting Start: Libs/NanoHTTPD/lib-nanohttpd.md
    - ❖ GStreamer:
      - GStreamer: Libs/GStreamer/gstreamer.md
      - Tải về: Libs/GStreamer/gstreamer-installing.md
      - Gst Tools: Libs/GStreamer/gstreamer-tools.md
      - ❖ Khái Niệm:
        - Concepts: Libs/GStreamer/gstreamer-gstreamer-concepts.md
        - ❖ Elements:
          - ❖ Source:
              - Video: Libs/GStreamer/gstreamer-element-video-source.md
              - Audio: Libs/GStreamer/gstreamer-tools-stream-video.md
              - Playbin: Libs/GStreamer/gstreamer-tools-stream-video.md
          - ❖ Elements:
              - Test: Libs/GStreamer/gstreamer-tools-stream-video.md
      - GStreamer Note: Libs/GStreamer/gstreamer-notebook.md
      - ❖ Basic Tutorials:
        - Tutorial: Libs/GStreamer/gstreamer-b-tutorial.md
        - Hello world!: Libs/GStreamer/gstreamer-b-hello-world.md
        - Đường Ống Động: Libs/GStreamer/gstreamer-b-dynamic-pipelines.md
        - Pipeline Graphs: Libs/GStreamer/gstreamer-b-pipeline-graphs.md
      - Stream Video: Libs/GStreamer/gstreamer-tools-stream-video.md
      - ❖ Pipeline Samples (Self):
        - Simple:  Libs/GStreamer/gstreamer-pipeline-samples-simple.md
      - ❖ Pipeline Samples:
        - Intro:  Libs/GStreamer/gstreamer-pipeline-samples.md
        - Tips for Debug: Libs/GStreamer/gstreamer-pipeline-samples-tips-for-debug.md
        - Video: Libs/GStreamer/gstreamer-pipeline-samples-video.md
        - Audio: Libs/GStreamer/gstreamer-pipeline-samples-audio.md
        - Mux Video and Audio: Libs/GStreamer/gstreamer-pipeline-samples-mux-video-and-audio.md
        - Media File: Libs/GStreamer/gstreamer-pipeline-samples-media-file.md
        - Network Streaming: Libs/GStreamer/gstreamer-pipeline-samples-network-streaming.md
        - Mixing: Libs/GStreamer/gstreamer-pipeline-samples-mixing.md
        - SHM (Shared Memory): Libs/GStreamer/gstreamer-pipeline-samples-shm.md
        - Fallbacksrc: Libs/GStreamer/gstreamer-pipeline-samples-fallbacksrc.md
        - Live Stream, ...: Libs/GStreamer/gstreamer-pipeline-samples-live-stream.md
        - Python Opencv: Libs/GStreamer/gstreamer-pipeline-samples-python-opencv.md
      - ❖ Another:
        - Graphs: Libs/GStreamer/gstreamer-pipeline-graphs.md
      - ❖ Ubuntu Tutorial:
        - Tutorial 1: Libs/GStreamer/gstreamer-ubuntu-tutorial-1.md
      - ❖ Bắt đầu với Windows:
        - Geting Start: Libs/GStreamer/gstreamer-windows.md
      - ❖ Bắt đầu với Android:
        - Geting Start: Libs/GStreamer/gstreamer-android.md
        - Dựng thư viện: Libs/GStreamer/gstreamer-android-build-gstreamer.md
        - ❖ Android Tutorial:
          - GStreamer 1: Libs/GStreamer/gstreamer-android-tutorial-1.md
          - GStreamer 2: Libs/GStreamer/gstreamer-android-tutorial-2.md
          - GStreamer 3: Libs/GStreamer/gstreamer-android-tutorial-3.md
          - GStreamer 4: Libs/GStreamer/gstreamer-android-tutorial-4.md
          - NamiDtv2Example:
            - NamiDtv2Example: Libs/GStreamer/gstreamer-android-nami-dtvbt2-example.md
            - Full Chart: Libs/GStreamer/gstreamer-android-nami-dtvbt2-example-full-chart.md
    - ❖ ROS2:
      - ROS2: Libs/ROS2/ros2.md
  ##################################################################################################################################
  - Git:
    - About Git: Git/git.md
    - Install: Git/git-install.md
    - SSH: Git/git-ssh.md
    - ❖ Common:
      - Git Config: Git/git-config.md
      - Git Clone: Git/git-clone.md
      - Git Branch: Git/git-branch.md
      - Git Ignore: Git/git-ignore.md
      - Git Diff: Git/git-diff.md
    - Git Example: Git/git-example.md
    - Git Beginer: Git/git-beginer.md
    - ❖ How to:
      - Custom Commands: Git/git-custom-commands.md
    - ❖ Github:
      - Github Overview: Git/Github/github-overview.md
      - Github Start: Git/Github/github-start.md
      - Github Page: Git/Github/github-page.md
  ##################################################################################################################################
  - Project:
    - ❖ Tad App: 
      - Mô tả: Project/Tad/project-tad-app.md
    - ❖ Pokedex: 
      - README: Project/Pokedex/project-pokedex.md

extra_css:
  - assets/stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - assets/scripts/tablesort.min.js
  - assets/scripts/tablesort.js
  - assets/scripts/katex.js
  - assets/scripts/keyevent.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

graph:
  enabled: true
  output_file: assets/network/graph.json
  include_homepage: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN