name: ci 
on:
  push:
    branches:
      - main
      - master
      - public
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .caches
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocs-network-graph-plugin
      - run: pip install mkdocs-macros-plugin
      - run: pip install mkdocs-markmap
      # - run: pip install pillow cairosvg
      - run: pip install mkdocs_puml
      - run: pip install mkdocs-puml
      - run: pip install mkdocs-plantuml
      - run: pip install mkdocs
      - run: pip install mkdocs_puml
      - run: pip install pymdown-extensions
      - run: mkdocs gh-deploy --force